name: jd_base
on:
   workflow_dispatch:
   watch:
    types: started
    push:
    branches: [ master ]
   schedule:
    - cron: '0 9-23/4 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run:
    name: Sync-Gitee-to-Github
    runs-on: ubuntu-latest
    steps:
    - name: Mirror the Github repos to Gitee.
      uses: fakedon/hub-mirror@main
      with:
        src: gitee/wudongdefeng
        dst: github/wudongdefeng
        dst_key: ${{ secrets.USER_PRIVATE_KEY }}
        dst_token: ${{ secrets.USER_TOKEN }}
        static_list: "jd-base"
        account_type: user
        force_update: true
