# This is a basic workflow to help you get started with Actions

name: sync to github

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  schedule:
    - cron: '30 */3 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run:
    name: Sync-Gitee-to-Github
    runs-on: ubuntu-latest
    steps:
    - name: Mirror the Github repos to Gitee.
      uses: fakedon/hub-mirror@main
      with:
        src: gitee/lxk0301
        dst: github/wudongdefeng
        dst_key: ${{ secrets.USER_PRIVATE_KEY }}
        dst_token: ${{ secrets.USER_TOKEN }}
        static_list: "jd_scripts"
        account_type: user
        force_update: true

      
